rule all:
    input: 
        "second.txt",
        "third.txt",
        "log_file.txt",
    script:
        "scripts/delete_files.py"



rule create_table:
    input: 
        "first.txt"
    output: 
        "second.txt"
    script: 
        "scripts/create_table.py"


rule insert_into_table:
    input: 
        "second.txt"
    output: 
        "third.txt"
    script: 
        "scripts/insert_into_table.py"

rule insert_another_data:
    input: 
        "third.txt"
    output: 
        "log_file.txt"
    script: 
        "scripts/insert_another_data.py"
